import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/* Per-repo sidebar. Four standard sections so every service site has the same
 * shape. `reference/*` is typically auto-generated (TypeDoc / pydoc-markdown)
 * and can be switched to {type:'autogenerated'} once generators are wired. */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    'overview',
    {
      type: 'category',
      label: 'Guides',
      link: {type: 'doc', id: 'guides/guides-index'},
      items: ['guides/getting-started', 'guides/api_usage'],
    },
    {
      type: 'category',
      label: 'API reference',
      link: {type: 'doc', id: 'api-reference/api-reference-index'},
      items: [],
      // When generators land, replace `items: []` above with:
      //   {type: 'autogenerated', dirName: 'api-reference'}
    },
    {
      type: 'category',
      label: 'Deep dives',
      link: {type: 'doc', id: 'deep-dives/deep-dives-index'},
      items: [],
    },
  ],
};

export default sidebars;
